import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function About() {
    return (
        <div className="min-h-screen bg-slate-50 font-sans text-slate-900 py-20 px-4">
            <div className="max-w-2xl mx-auto bg-white/80 backdrop-blur-sm rounded-3xl p-10 border border-white/50 shadow-sm">

                <Link href="/" className="inline-flex items-center text-sm text-slate-500 hover:text-blue-600 mb-8 transition-colors group">
                    <ArrowLeft size={16} className="mr-1 group-hover:-translate-x-1 transition-transform" />
                    Back to News
                </Link>

                <h1 className="text-3xl font-extrabold text-slate-900 mb-2">About Us</h1>
                <p className="text-slate-500 text-lg mb-10">Global Medical Insight について</p>

                <div className="space-y-8">
                    <section>
                        <h2 className="text-sm font-bold text-blue-600 uppercase tracking-wider mb-3">Our Mission</h2>
                        <p className="leading-relaxed text-slate-700">
                            当サイトは、アフリカ・中東・南アジアにおける急速な医療市場の成長と変化を捉え、
                            日本の医療・製薬業界の皆様にタイムリーな情報を提供することを目的としています。
                        </p>
                    </section>

                    <section>
                        <h2 className="text-sm font-bold text-blue-600 uppercase tracking-wider mb-3">Technology & Data</h2>
                        <p className="leading-relaxed text-slate-700 mb-4">
                            最新のAI技術を活用し、現地の膨大なニュースの中から重要なトピックを厳選・要約しています。
                        </p>
                        <ul className="text-sm text-slate-600 space-y-2 bg-slate-50 p-4 rounded-xl border border-slate-100">
                            <li className="flex items-center gap-2">
                                <span className="w-1.5 h-1.5 bg-slate-400 rounded-full"></span>
                                Headlines provided by <a href="https://newsapi.org" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">NewsAPI.org</a>
                            </li>
                            <li className="flex items-center gap-2">
                                <span className="w-1.5 h-1.5 bg-slate-400 rounded-full"></span>
                                Summaries generated by <strong>Google Gemini 2.0 Flash Lite</strong>
                            </li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-sm font-bold text-blue-600 uppercase tracking-wider mb-3">Disclaimer</h2>
                        <p className="text-sm text-slate-500 leading-relaxed">
                            掲載されている記事の要約および分析はAIによって自動生成されたものです。
                            正確性の確保には努めておりますが、投資や業務上の判断を行う際は、必ず一次情報（元記事）をご確認ください。
                        </p>
                    </section>
                </div>

                <div className="mt-12 pt-8 border-t border-slate-100 text-center">
                    <p className="text-xs text-slate-400">© 2025 Global Medical Insight. All rights reserved.</p>
                </div>
            </div>
        </div>
    );
}
